// <auto-generated />
namespace Data.Services.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddChannelApiFunction : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddChannelApiFunction));
        
        string IMigrationMetadata.Id
        {
            get { return "201705121453194_AddChannelApiFunction"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
