namespace Infrastructure.Contracts.Services.Security
{
    /// <summary>
    /// Interface for User Authentication Service.
    /// </summary>
    public interface IPasswordHashService
    {
        /// <summary>
        /// Validates user password.
        /// </summary>
        /// <param name="password">Plain text user password.</param>
        /// <param name="passwordHash">Hashed user password from database.</param>
        /// <param name="passwordSalt">User password salt from database.</param>
        /// <returns>Returns true if password is valid.</returns>
        bool ValidatePassword(string password, string passwordHash, string passwordSalt);

        /// <summary>
        /// Creates user password hash.
        /// </summary>
        /// <param name="password">Plain text user password.</param>
        /// <param name="passwordSalt">Autogenerated password salt.</param>
        /// <returns>Returns hashed password.</returns>
        string CreatePasswordHash(string password, string passwordSalt);
    }
}