//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shared.Resources.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Gene.
        /// </summary>
        public static string App_Title {
            get {
                return ResourceManager.GetString("App_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no available channel configured for nucleotide: {0}.
        /// </summary>
        public static string ChannelNotConfigured {
            get {
                return ResourceManager.GetString("ChannelNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gene fragments should correspond to configured channels..
        /// </summary>
        public static string GeneSynthesizer_ChannelsConfigurationError {
            get {
                return ResourceManager.GetString("GeneSynthesizer_ChannelsConfigurationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All valves deactivated.
        /// </summary>
        public static string Infrastructure_AllValvesDeactivatedMsg {
            get {
                return ResourceManager.GetString("Infrastructure_AllValvesDeactivatedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot login to Auto Gene. Please check your connectivity and try again..
        /// </summary>
        public static string Login_ConnectivityError {
            get {
                return ResourceManager.GetString("Login_ConnectivityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Login_EmailEntryPlaceholder {
            get {
                return ResourceManager.GetString("Login_EmailEntryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Please enter a valid e-mail  .
        /// </summary>
        public static string Login_EmailEntryValidationMsg {
            get {
                return ResourceManager.GetString("Login_EmailEntryValidationMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string Login_LogInButton {
            get {
                return ResourceManager.GetString("Login_LogInButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Login_PasswordEntryPlaceholder {
            get {
                return ResourceManager.GetString("Login_PasswordEntryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string Login_Title {
            get {
                return ResourceManager.GetString("Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email you&apos;ve entered doesn&apos;t match any account..
        /// </summary>
        public static string Login_UserNotFound {
            get {
                return ResourceManager.GetString("Login_UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no good internet connection.
        /// </summary>
        public static string Logs_NoInternetConnection {
            get {
                return ResourceManager.GetString("Logs_NoInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no good connection to synthesizer.
        /// </summary>
        public static string Logs_NoSynthesizerConnection {
            get {
                return ResourceManager.GetString("Logs_NoSynthesizerConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Logs_Settings {
            get {
                return ResourceManager.GetString("Logs_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Logs.
        /// </summary>
        public static string Logs_Title {
            get {
                return ResourceManager.GetString("Logs_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backend Api Url.
        /// </summary>
        public static string SynthesizerSettings_BackendApiUrl {
            get {
                return ResourceManager.GetString("SynthesizerSettings_BackendApiUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay after Strike On.
        /// </summary>
        public static string SynthesizerSettings_DelayAfterStrikeOn {
            get {
                return ResourceManager.GetString("SynthesizerSettings_DelayAfterStrikeOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SynthesizerSettings_Save {
            get {
                return ResourceManager.GetString("SynthesizerSettings_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Settings Failed.
        /// </summary>
        public static string SynthesizerSettings_SaveSettingsFailedMsg {
            get {
                return ResourceManager.GetString("SynthesizerSettings_SaveSettingsFailedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synthesizer Api Url.
        /// </summary>
        public static string SynthesizerSettings_SynthesizerApiUrl {
            get {
                return ResourceManager.GetString("SynthesizerSettings_SynthesizerApiUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synthesizer Settings.
        /// </summary>
        public static string SynthesizerSettings_Title {
            get {
                return ResourceManager.GetString("SynthesizerSettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Monitor.
        /// </summary>
        public static string SystemMonitor_Title {
            get {
                return ResourceManager.GetString("SystemMonitor_Title", resourceCulture);
            }
        }
    }
}
