//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommonResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shared.Resources.CommonResources", typeof(CommonResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SynTau.
        /// </summary>
        internal static string App_Title {
            get {
                return ResourceManager.GetString("App_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must match.
        /// </summary>
        internal static string CreateAccount_ConfirmPasswordErrorMessage {
            get {
                return ResourceManager.GetString("CreateAccount_ConfirmPasswordErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string CreateAccount_ConfirmPasswordPlaceholder {
            get {
                return ResourceManager.GetString("CreateAccount_ConfirmPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your password.
        /// </summary>
        internal static string CreateAccount_ConfirmPasswordRequiredValidationMessage {
            get {
                return ResourceManager.GetString("CreateAccount_ConfirmPasswordRequiredValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string CreateAccount_FirstNamePlaceholder {
            get {
                return ResourceManager.GetString("CreateAccount_FirstNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your first name.
        /// </summary>
        internal static string CreateAccount_FirstNameRequiredMessage {
            get {
                return ResourceManager.GetString("CreateAccount_FirstNameRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter first name.
        /// </summary>
        internal static string CreateAccount_FirstNameRequiredValidationMessage {
            get {
                return ResourceManager.GetString("CreateAccount_FirstNameRequiredValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create account.
        /// </summary>
        internal static string CreateAccount_FormTitle {
            get {
                return ResourceManager.GetString("CreateAccount_FormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string CreateAccount_LastNamePlaceholder {
            get {
                return ResourceManager.GetString("CreateAccount_LastNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your last name.
        /// </summary>
        internal static string CreateAccount_LastNameRequiredMessage {
            get {
                return ResourceManager.GetString("CreateAccount_LastNameRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter last name.
        /// </summary>
        internal static string CreateAccount_LastNameRequiredValidationMessage {
            get {
                return ResourceManager.GetString("CreateAccount_LastNameRequiredValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account? Sign-In &gt;.
        /// </summary>
        internal static string CreateAccount_LoginButton {
            get {
                return ResourceManager.GetString("CreateAccount_LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use 8 characters or more for your password.
        /// </summary>
        internal static string CreateAccount_PasswordStrengthErrorMessage {
            get {
                return ResourceManager.GetString("CreateAccount_PasswordStrengthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a combination of at least six numbers, letters and punctuation marks (like ! and &amp;)..
        /// </summary>
        internal static string CreateAccount_PasswordStrengthErrorMessage2 {
            get {
                return ResourceManager.GetString("CreateAccount_PasswordStrengthErrorMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address already in use.
        /// </summary>
        internal static string CreateAccount_UserDuplicateErrorMessage {
            get {
                return ResourceManager.GetString("CreateAccount_UserDuplicateErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Account.
        /// </summary>
        internal static string Login_CreateAccount_CreateAccountButton {
            get {
                return ResourceManager.GetString("Login_CreateAccount_CreateAccountButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid email address.
        /// </summary>
        internal static string Login_CreateAccount_EmailIsNotValidMessage {
            get {
                return ResourceManager.GetString("Login_CreateAccount_EmailIsNotValidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Login_CreateAccount_EmailPlaceholder {
            get {
                return ResourceManager.GetString("Login_CreateAccount_EmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email.
        /// </summary>
        internal static string Login_CreateAccount_EmailRequiredMessage {
            get {
                return ResourceManager.GetString("Login_CreateAccount_EmailRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Login_CreateAccount_PasswordPlaceholder {
            get {
                return ResourceManager.GetString("Login_CreateAccount_PasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password.
        /// </summary>
        internal static string Login_CreateAccount_PasswordRequiredMessage {
            get {
                return ResourceManager.GetString("Login_CreateAccount_PasswordRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        internal static string Login_ForgotPasswordButton {
            get {
                return ResourceManager.GetString("Login_ForgotPasswordButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign-In.
        /// </summary>
        internal static string Login_FormTitle {
            get {
                return ResourceManager.GetString("Login_FormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password is incorrect.
        /// </summary>
        internal static string Login_IncorrectPasswordErrorMessage {
            get {
                return ResourceManager.GetString("Login_IncorrectPasswordErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign-In.
        /// </summary>
        internal static string Login_LoginButton {
            get {
                return ResourceManager.GetString("Login_LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        internal static string Login_OrDivider {
            get {
                return ResourceManager.GetString("Login_OrDivider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep me signed in.
        /// </summary>
        internal static string Login_RememberMeLabel {
            get {
                return ResourceManager.GetString("Login_RememberMeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We cannot find an account with that email address.
        /// </summary>
        internal static string Login_UserNotFoundErrorMessage {
            get {
                return ResourceManager.GetString("Login_UserNotFoundErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string UserProfile_Logout {
            get {
                return ResourceManager.GetString("UserProfile_Logout", resourceCulture);
            }
        }
    }
}
